package io.twodigits.todo.model;

import java.util.Objects;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

@DynamoDBTable(tableName = "todo")
public class TodoDynamoDb {
  private String id;
	private String text;
  private Boolean done;

  public TodoDynamoDb() {
  }

  public TodoDynamoDb(String text, Boolean done) {
    this.text = text;
    this.done = done;
  }

  @DynamoDBHashKey
  @DynamoDBAutoGeneratedKey
  public String getId() {
    return this.id;
  }

  public void setId(String id) {
    this.id = id;
  }

  @DynamoDBAttribute
  public String getText() {
    return this.text;
  }

  public void setText(String text) {
    this.text = text;
  }

  @DynamoDBAttribute
  public Boolean getDone() {
    return this.done;
  }

  public void setDone(Boolean done) {
    this.done = done;
  }

  @Override
  public boolean equals(Object o) {
    if (o == this)
      return true;
    if (!(o instanceof TodoDynamoDb)) {
      return false;
    }
    TodoDynamoDb todoDynamoDb = (TodoDynamoDb) o;
    return Objects.equals(id, todoDynamoDb.id) && Objects.equals(text, todoDynamoDb.text) && Objects.equals(done, todoDynamoDb.done);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, text, done);
  }

  @Override
  public String toString() {
    return "{" +
      " id='" + getId() + "'" +
      ", text='" + getText() + "'" +
      ", done='" + getDone() + "'" +
      "}";
  }

}